spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/JdataExam?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: "000411"
  redis:
    port: 6380
    host: 127.0.0.1
    password: "000411"
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

mybatis:
  type-aliases-package: cn.edu.swpu.jdata_exam.entity
  mapper-locations: classpath:mapper/*.xml
server:
  port: 5488
  connection-timeout: 120





